#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) < 2:
	imsi = ""
else:
	imsi = sys.argv[1];

manager = dbus.Interface(bus.get_object('com.intel.provman.server', '/com/intel/provman'),
					'com.intel.provman.Settings')
manager.Start(imsi)
manager.Set("/telephony/contexts/test/apn","test-apn")
manager.Set("/telephony/contexts/test/name","Test APN")
manager.Set("/telephony/contexts/test/username","markus")
manager.Set("/telephony/contexts/test/password","tulius")
manager.End()
