#!/usr/bin/python

import dbus
import sys

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object('com.intel.provman.server', '/com/intel/provman'),
					'com.intel.provman.Settings')
manager.Start("")
manager.Set("/applications/sync/pompey/username","the great")
manager.Set("/applications/sync/pompey/password","Septimus")
manager.Set("/applications/sync/pompey/url","http://localhost")
manager.Set("/applications/sync/pompey/name","The Warden of Land and Sea")
manager.End()
