#!/usr/bin/python

import dbus
import sys

bus = dbus.SessionBus()

if len(sys.argv) < 2:
	print "Usage: del key [imsi]\n"
	System.Exit(1)

key = sys.argv[1]

if len(sys.argv) < 3:
	imsi = ""
else:
	imsi = sys.argv[2];

manager = dbus.Interface(bus.get_object('com.intel.provman.server', '/com/intel/provman'),
					'com.intel.provman.Settings')
manager.Start(imsi)
try:
	manager.Delete(key)
except dbus.exceptions.DBusException:
	pass
manager.End()
